/*This is tone file*/

const char* tone_uri[] = {
   "flash://tone/0_alarm.mp3",
   "flash://tone/1_bad.mp3",
   "flash://tone/2_batterie_low.mp3",
   "flash://tone/3_beep.mp3",
   "flash://tone/4_bluebot_deleteAll.mp3",
   "flash://tone/5_bluebot_deleteLast.mp3",
   "flash://tone/6_bluebot_endPath.mp3",
   "flash://tone/7_bluetooth_connexion.mp3",
   "flash://tone/8_codeError.mp3",
   "flash://tone/9_codeExecSucess.mp3",
   "flash://tone/10_detect.mp3",
   "flash://tone/11_draw_end.mp3",
   "flash://tone/12_fleches.mp3",
   "flash://tone/13_instru_balafon_00.mp3",
   "flash://tone/14_instru_balafon_01.mp3",
   "flash://tone/15_instru_balafon_02.mp3",
   "flash://tone/16_instru_balafon_03.mp3",
   "flash://tone/17_instru_balafon_04.mp3",
   "flash://tone/18_instru_balafon_05.mp3",
   "flash://tone/19_instru_flute_00.mp3",
   "flash://tone/20_instru_flute_01.mp3",
   "flash://tone/21_instru_flute_02.mp3",
   "flash://tone/22_instru_flute_03.mp3",
   "flash://tone/23_instru_flute_04.mp3",
   "flash://tone/24_instru_flute_05.mp3",
   "flash://tone/25_instru_guitare_00.mp3",
   "flash://tone/26_instru_guitare_01.mp3",
   "flash://tone/27_instru_guitare_02.mp3",
   "flash://tone/28_instru_guitare_03.mp3",
   "flash://tone/29_instru_guitare_04.mp3",
   "flash://tone/30_instru_guitare_05.mp3",
   "flash://tone/31_instru_orchestre_00.mp3",
   "flash://tone/32_instru_orchestre_01.mp3",
   "flash://tone/33_instru_orchestre_02.mp3",
   "flash://tone/34_instru_orchestre_03.mp3",
   "flash://tone/35_instru_orchestre_04.mp3",
   "flash://tone/36_instru_orchestre_05.mp3",
   "flash://tone/37_instru_piano_00.mp3",
   "flash://tone/38_instru_piano_01.mp3",
   "flash://tone/39_instru_piano_02.mp3",
   "flash://tone/40_instru_piano_03.mp3",
   "flash://tone/41_instru_piano_04.mp3",
   "flash://tone/42_instru_piano_05.mp3",
   "flash://tone/43_instru_violon_00.mp3",
   "flash://tone/44_instru_violon_01.mp3",
   "flash://tone/45_instru_violon_02.mp3",
   "flash://tone/46_instru_violon_03.mp3",
   "flash://tone/47_instru_violon_04.mp3",
   "flash://tone/48_instru_violon_05.mp3",
   "flash://tone/49_intro.mp3",
   "flash://tone/50_notify.mp3",
   "flash://tone/51_outro.mp3",
   "flash://tone/52_red_freeFall.mp3",
   "flash://tone/53_red_prisonnier.mp3",
   "flash://tone/54_red_tap.mp3",
   "flash://tone/55_rond.mp3",
};

int get_tone_uri_num()
{
    return sizeof(tone_uri) / sizeof(char *) - 1;
}
